name: BedrockTextureLib
main: fr.prodrivers.bukkit.bedrocktexturelib.BedrockTextureLib
version: ${project.version}
description: ${project.description}
depend: [ProdriversCommons]
softdepend: [Geyser-Spigot]
api-version: "1.17"

commands:
  bedrocktexturelib:
    description: Main BedrockTextureLib command
  bedrocktexturelib reload:
    description: Reload BedrockTextureLib to a fresh state
    permission: bedrockutil.reload

permissions:
  bedrocktexturelib.help:
    description: Allows a user to see the commands help
    default: op
  bedrocktexturelib.reload:
    description: Allows a user to use the reload command
    default: op